name = "Create Modpack"
author = "Bharath Nair"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "335751bf909a7943ec052ab6ca437760f1b40260cd0fea5f208be7362690b8a4"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
