name = "Create Modpack"
author = "Bharath Nair"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72cd716d434455c297f697d0023cdc404a069b89cbd3f18ecc538d00cb00cb2c"

[versions]
forge = "47.3.6"
minecraft = "1.20.1"
